In [1]:
import  pandas as pd


df = pd.read_csv(r"Activity1.01/sales.csv", sep = ",")
df.head()

,Year,Product,line,Product.1,type,Product.2,Order,method,type.1,Retailer,country,Revenue
0,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,United,States,315044.33
1,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Canada,NaN,14313.48
2,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Mexico,NaN,156644.47
3,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Brazil,NaN,59191.72
4,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Japan,NaN,7029.33

##  Exercise 1.01

In [2]:
user_info = pd.read_json(r"Exercise1.01/user_info.json")
user_info.head()

,_id,index,guid,isActive,balance,picture,age,eyeColor,name,gender,...,phone,address,about,registered,latitude,longitude,tags,friends,greeting,favoriteFruit
0,5c0a28d7a647437fd3d3a6aa,0,832f1af4-fb18-4ba8-b032-f4cbf343dbe9,False,"$3,806.93",http://placehold.it/32x32,20,green,Grace Berry,female,...,+1 (814) 555-3298,"698 Kansas Place, Bethpage, Louisiana, 7695",Nostrud consectetur elit occaecat dolore incid...,2015-12-09T08:21:48 -06:-30,-65.630631,131.991768,"[eu, id, fugiat, deserunt, nulla, proident, la...","[{'id': 0, 'name': 'Small Pena'}, {'id': 1, 'n...","Hello, Grace Berry! You have 1 unread messages.",strawberry
1,5c0a28d780f6278b11586ab1,1,4306cb37-9506-48c2-8ccf-e69a063589ee,True,"$3,330.01",http://placehold.it/32x32,22,brown,Hilary Sellers,female,...,+1 (942) 536-3059,"309 Kingsway Place, Kilbourne, New York, 3771",Sunt id ipsum velit voluptate. Ullamco non non...,2014-12-15T11:42:39 -06:-30,38.790260,48.442002,"[deserunt, do, adipisicing, in, aliqua, duis, ...","[{'id': 0, 'name': 'Spears Smith'}, {'id': 1, ...","Hello, Hilary Sellers! You have 4 unread messa...",apple
2,5c0a28d722e2e29d9bce2b64,2,5019e436-7cc4-48ee-a384-3483131f8ee1,True,"$1,619.46",http://placehold.it/32x32,40,green,Sherri Gilbert,female,...,+1 (954) 591-2183,"347 Seeley Street, Witmer, Kansas, 9369",Laborum ad excepteur amet sunt aliqua veniam c...,2014-10-31T05:02:03 -06:-30,34.404508,-116.452211,"[adipisicing, cillum, deserunt, aute, ipsum, c...","[{'id': 0, 'name': 'Sexton Watts'}, {'id': 1, ...","Hello, Sherri Gilbert! You have 1 unread messa...",apple
3,5c0a28d76b5e8859a754cb4f,3,d2c4b1eb-2974-463a-b288-d1dae5dec187,False,"$3,334.12",http://placehold.it/32x32,29,blue,Caldwell Patterson,male,...,+1 (815) 400-3780,"178 Stewart Street, Ferney, Wyoming, 9118",Eu amet aliqua magna ipsum quis et ut reprehen...,2018-04-02T03:06:31 -06:-30,-63.424959,-51.151783,"[adipisicing, veniam, dolor, duis, aute, tempo...","[{'id': 0, 'name': 'Anne Holcomb'}, {'id': 1, ...","Hello, Caldwell Patterson! You have 6 unread m...",strawberry
4,5c0a28d7ebb99c08e2288c76,4,df0b59ed-2e81-43f1-9ae0-16f138e738be,False,"$1,368.48",http://placehold.it/32x32,33,brown,Head Mcconnell,male,...,+1 (820) 573-3154,"189 Rogers Avenue, Lindisfarne, Mississippi, 1961",Sunt amet exercitation aliqua cillum commodo o...,2016-01-06T09:38:15 -06:-30,-80.136744,176.780600,"[qui, aute, voluptate, eiusmod, est, est, cupi...","[{'id': 0, 'name': 'Elnora Peck'}, {'id': 1, '...","Hello, Head Mcconnell! You have 5 unread messa...",strawberry

In [3]:
user_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _id            6 non-null      object
 1   index          6 non-null      int64
 2   guid           6 non-null      object
 3   isActive       6 non-null      bool
 4   balance        6 non-null      object
 5   picture        6 non-null      object
 6   age            6 non-null      int64
 7   eyeColor       6 non-null      object
 8   name           6 non-null      object
 9   gender         6 non-null      object
 10  company        6 non-null      object
 11  email          6 non-null      object
 12  phone          6 non-null      object
 13  address        6 non-null      object
 14  about          6 non-null      object
 15  registered     6 non-null      object
 16  latitude       6 non-null      float64
 17  longitude      6 non-null      float64
 18  tags           6 non-null      object
 19  friends        6 non-null      object
 20  greeting       6 non-null      object
 21  favoriteFruit  6 non-null      object
dtypes: bool(1), float64(2), int64(2), object(17)
memory usage: 1.1+ KB

In [4]:
user_info.shape

(6, 22)

### Exercise 1.02

In [5]:
campaign_data = pd.read_csv(r'Exercise1.02/data.csv', sep = ',', header = 1)
campaign_data.head()

    views  likes
0   90006    402
1  101141    389
2   97297    403
3  117182    397
4   99637    404

### Exercise 1.03

In [6]:
df1 = pd.read_csv(r'Exercise1.03/timeSpent.csv', sep = ',', index_col = 0)

df2  = pd.read_csv(r'Exercise1.03/cost.csv', sep = ',', index_col = 0, skiprows = 0)

print(df1.head())
print(df2.head())

           timeSpent
users
Sushmita   31.266056
Adam       17.900529
Benny     265.236086
Anurag     42.470696
          cost
users
Adam      20.0
Anurag     NaN
Benny     15.0
Sushmita   2.0
Apoorva    7.0

In [7]:
df = df1.merge(df2, on='users', how='left')
df

           timeSpent  cost
users
Sushmita   31.266056   2.0
Adam       17.900529  20.0
Benny     265.236086  15.0
Anurag     42.470696   NaN

In [8]:
df.fillna(0, inplace=True)
df

           timeSpent  cost
users
Sushmita   31.266056   2.0
Adam       17.900529  20.0
Benny     265.236086  15.0
Anurag     42.470696   0.0

In [9]:
df.describe()

        timeSpent       cost
count    4.000000   4.000000
mean    89.218342   9.250000
std    117.774200   9.776673
min     17.900529   0.000000
25%     27.924674   1.500000
50%     36.868376   8.500000
75%     98.162044  16.250000
max    265.236086  20.000000

In [10]:
num_users = df.index.nunique()
num_users

marketing_budget = df['cost'].mean()  * num_users
marketing_budget

np.float64(37.0)

In [11]:
user_info

,_id,index,guid,isActive,balance,picture,age,eyeColor,name,gender,...,phone,address,about,registered,latitude,longitude,tags,friends,greeting,favoriteFruit
0,5c0a28d7a647437fd3d3a6aa,0,832f1af4-fb18-4ba8-b032-f4cbf343dbe9,False,"$3,806.93",http://placehold.it/32x32,20,green,Grace Berry,female,...,+1 (814) 555-3298,"698 Kansas Place, Bethpage, Louisiana, 7695",Nostrud consectetur elit occaecat dolore incid...,2015-12-09T08:21:48 -06:-30,-65.630631,131.991768,"[eu, id, fugiat, deserunt, nulla, proident, la...","[{'id': 0, 'name': 'Small Pena'}, {'id': 1, 'n...","Hello, Grace Berry! You have 1 unread messages.",strawberry
1,5c0a28d780f6278b11586ab1,1,4306cb37-9506-48c2-8ccf-e69a063589ee,True,"$3,330.01",http://placehold.it/32x32,22,brown,Hilary Sellers,female,...,+1 (942) 536-3059,"309 Kingsway Place, Kilbourne, New York, 3771",Sunt id ipsum velit voluptate. Ullamco non non...,2014-12-15T11:42:39 -06:-30,38.790260,48.442002,"[deserunt, do, adipisicing, in, aliqua, duis, ...","[{'id': 0, 'name': 'Spears Smith'}, {'id': 1, ...","Hello, Hilary Sellers! You have 4 unread messa...",apple
2,5c0a28d722e2e29d9bce2b64,2,5019e436-7cc4-48ee-a384-3483131f8ee1,True,"$1,619.46",http://placehold.it/32x32,40,green,Sherri Gilbert,female,...,+1 (954) 591-2183,"347 Seeley Street, Witmer, Kansas, 9369",Laborum ad excepteur amet sunt aliqua veniam c...,2014-10-31T05:02:03 -06:-30,34.404508,-116.452211,"[adipisicing, cillum, deserunt, aute, ipsum, c...","[{'id': 0, 'name': 'Sexton Watts'}, {'id': 1, ...","Hello, Sherri Gilbert! You have 1 unread messa...",apple
3,5c0a28d76b5e8859a754cb4f,3,d2c4b1eb-2974-463a-b288-d1dae5dec187,False,"$3,334.12",http://placehold.it/32x32,29,blue,Caldwell Patterson,male,...,+1 (815) 400-3780,"178 Stewart Street, Ferney, Wyoming, 9118",Eu amet aliqua magna ipsum quis et ut reprehen...,2018-04-02T03:06:31 -06:-30,-63.424959,-51.151783,"[adipisicing, veniam, dolor, duis, aute, tempo...","[{'id': 0, 'name': 'Anne Holcomb'}, {'id': 1, ...","Hello, Caldwell Patterson! You have 6 unread m...",strawberry
4,5c0a28d7ebb99c08e2288c76,4,df0b59ed-2e81-43f1-9ae0-16f138e738be,False,"$1,368.48",http://placehold.it/32x32,33,brown,Head Mcconnell,male,...,+1 (820) 573-3154,"189 Rogers Avenue, Lindisfarne, Mississippi, 1961",Sunt amet exercitation aliqua cillum commodo o...,2016-01-06T09:38:15 -06:-30,-80.136744,176.780600,"[qui, aute, voluptate, eiusmod, est, est, cupi...","[{'id': 0, 'name': 'Elnora Peck'}, {'id': 1, '...","Hello, Head Mcconnell! You have 5 unread messa...",strawberry
5,5c0a28d749ce43912931715e,5,1d4dcbcd-c5b7-45a8-9650-82d7f98305c6,True,"$2,441.66",http://placehold.it/32x32,23,green,Albert Lopez,male,...,+1 (971) 446-2770,"311 Haring Street, Savannah, Michigan, 9161",Occaecat dolor minim et nisi cupidatat ipsum. ...,2018-08-03T04:18:49 -06:-30,46.397226,148.006522,"[dolore, eiusmod, laborum, dolore, aliquip, al...","[{'id': 0, 'name': 'Candice Moreno'}, {'id': 1...","Hello, Albert Lopez! You have 2 unread messages.",apple

### Complete the Activity

In [12]:
sales =  pd.read_csv(r"Activity1.01/sales.csv", sep = ",")
sales.head()

,Year,Product,line,Product.1,type,Product.2,Order,method,type.1,Retailer,country,Revenue
0,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,United,States,315044.33
1,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Canada,NaN,14313.48
2,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Mexico,NaN,156644.47
3,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Brazil,NaN,59191.72
4,2004,Camping,Equipment,Cooking,Gear,TrailChef,Water,Bag,Telephone,Japan,NaN,7029.33

In [13]:
sales['order_method']= sales['type.1']
sales['product_line'] = sales['Product'] + ' ' + sales['line']
sales['product_type'] = sales['Product.1'] + ' ' + sales['type']
sales['Product1'] = sales['Product.2'] + ' ' + sales['Order'] + ' ' + sales['method']
sales['country'] = sales['country'].fillna(' ')
sales['retailer_country']= sales['Retailer'] + ' ' + sales['country']
sales = sales.drop(columns=['Product', 'line', 'Product.1', 'type', 'Product.2', 'Order', 'method', 'type.1', 'Retailer', 'country'], axis=1)

sales.head()

,Year,Revenue,order_method,product_line,product_type,Product1,retailer_country
0,2004,315044.33,Telephone,Camping Equipment,Cooking Gear,TrailChef Water Bag,United States
1,2004,14313.48,Telephone,Camping Equipment,Cooking Gear,TrailChef Water Bag,Canada
2,2004,156644.47,Telephone,Camping Equipment,Cooking Gear,TrailChef Water Bag,Mexico
3,2004,59191.72,Telephone,Camping Equipment,Cooking Gear,TrailChef Water Bag,Brazil
4,2004,7029.33,Telephone,Camping Equipment,Cooking Gear,TrailChef Water Bag,Japan

In [15]:
sales.describe()

         Year        Revenue
count   100.0     100.000000
mean   2004.0   75543.366300
std       0.0   70060.167447
min    2004.0    6615.840000
25%    2004.0   32575.022500
50%    2004.0   59479.910000
75%    2004.0   78551.192500
max    2004.0  348446.250000

In [17]:
import duckdb
duckdb.sql("SELECT * FROM sales LIMIT 5")

┌───────┬───────────┬──────────────┬───────────────────┬──────────────┬─────────────────────┬──────────────────┐
│ Year  │  Revenue  │ order_method │   product_line    │ product_type │      Product1       │ retailer_country │
│ int64 │  double   │   varchar    │      varchar      │   varchar    │       varchar       │     varchar      │
├───────┼───────────┼──────────────┼───────────────────┼──────────────┼─────────────────────┼──────────────────┤
│  2004 │ 315044.33 │ Telephone    │ Camping Equipment │ Cooking Gear │ TrailChef Water Bag │ United States    │
│  2004 │  14313.48 │ Telephone    │ Camping Equipment │ Cooking Gear │ TrailChef Water Bag │ Canada           │
│  2004 │ 156644.47 │ Telephone    │ Camping Equipment │ Cooking Gear │ TrailChef Water Bag │ Mexico           │
│  2004 │  59191.72 │ Telephone    │ Camping Equipment │ Cooking Gear │ TrailChef Water Bag │ Brazil           │
│  2004 │   7029.33 │ Telephone    │ Camping Equipment │ Cooking Gear │ TrailChef Water Bag │ Japan            │
└───────┴───────────┴──────────────┴───────────────────┴──────────────┴─────────────────────┴──────────────────┘

In [19]:
duckdb.sql('select distinct retailer_country from sales').df()

   retailer_country
0          Brazil
1     Netherlands
2         Austria
3          United
4         Finland
5           Italy
6          Mexico
7           Spain
8         Denmark
9    United Kingdom
10    United States
11         Canada
12          China
13         Sweden
14          Japan
15          Korea
16      Singapore
17      Australia
18    Switzerland
19         France
20        Germany
21        Belgium

In [20]:
duckdb.sql('select  retailer_country from sales').df().value_counts()

retailer_country
Australia           5
Brazil              5
China               5
Canada              5
Finland             5
Denmark             5
Sweden              5
Singapore           5
France              5
Germany             5
Japan               5
Korea               5
Mexico              5
Netherlands         5
United Kingdom      5
Austria             4
Belgium             4
Italy               4
Spain               4
Switzerland         4
United States       4
United              1
Name: count, dtype: int64

In [21]:
(duckdb.sql("SELECT retailer_country FROM sales").df()
    ['retailer_country']
    .value_counts()
    .rename_axis('retailer_country')
    .reset_index(name='n'))

   retailer_country  n
0          Canada    5
1          Mexico    5
2           Japan    5
3          Brazil    5
4           Korea    5
5           China    5
6         Germany    5
7       Singapore    5
8       Australia    5
9     Netherlands    5
10         Sweden    5
11        Finland    5
12        Denmark    5
13         France    5
14   United Kingdom  5
15    United States  4
16        Belgium    4
17    Switzerland    4
18        Austria    4
19          Italy    4
20          Spain    4
21         United    1